# Generated by Django 4.0.5 on 2022-07-20 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='films',
            name='description',
        ),
        migrations.RemoveField(
            model_name='films',
            name='special',
        ),
        migrations.AddField(
            model_name='films',
            name='genre',
            field=models.CharField(default='Action', max_length=30),
        ),
        migrations.AddField(
            model_name='films',
            name='star',
            field=models.FloatField(default=5.0),
        ),
    ]
