# Generated by Django 4.0.5 on 2022-08-02 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_remove_films_description_remove_films_special_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='films',
            name='actors',
            field=models.TextField(default='Sanywa John', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='films',
            name='runtime',
            field=models.IntegerField(default=60),
        ),
    ]
