# Generated by Django 4.0.5 on 2022-08-02 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_films_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='films',
            name='description',
            field=models.TextField(default='it is one of the greatest movies everyone anticipated to watch. The characters fit in well.'),
            preserve_default=False,
        ),
    ]
