# Generated by Django 4.0.5 on 2022-08-05 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_films_is_coming_soon_films_is_popular_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='films',
            name='price',
            field=models.IntegerField(default=10000),
        ),
    ]
